# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cadastro.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class cadastro(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(744, 596)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(290, 10, 291, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(100, 150, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(100, 210, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.confirm_4 = QtWidgets.QPushButton(Form)
        self.confirm_4.setGeometry(QtCore.QRect(0, 550, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.confirm_4.setFont(font)
        self.confirm_4.setStyleSheet("QPushButton {\n"
"    background-color:White;\n"
"    color: black;\n"
"    border-radius: 10px;\n"
"    border: 2px solid black;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: Gray;\n"
"    color: white;\n"
"    border: 2px solid white;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:Gray;\n"
"    border: 2px solid yellow;\n"
"}")
        self.confirm_4.setObjectName("confirm_4")
        self.confirm_5 = QtWidgets.QPushButton(Form)
        self.confirm_5.setGeometry(QtCore.QRect(290, 300, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.confirm_5.setFont(font)
        self.confirm_5.setStyleSheet("QPushButton {\n"
"    background-color:White;\n"
"    color: black;\n"
"    border-radius: 10px;\n"
"    border: 2px solid black;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: Gray;\n"
"    color: white;\n"
"    border: 2px solid white;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:Gray;\n"
"    border: 2px solid yellow;\n"
"}")
        self.confirm_5.setObjectName("confirm_5")
        self.traducao_2 = QtWidgets.QLineEdit(Form)
        self.traducao_2.setGeometry(QtCore.QRect(180, 150, 391, 41))
        font = QtGui.QFont()
        font.setFamily("Nirmala Text")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.traducao_2.setFont(font)
        self.traducao_2.setStyleSheet("background-color: lightblue; /* Azul claro */\n"
"")
        self.traducao_2.setText("")
        self.traducao_2.setObjectName("traducao_2")
        self.traducao_3 = QtWidgets.QLineEdit(Form)
        self.traducao_3.setGeometry(QtCore.QRect(180, 200, 391, 41))
        font = QtGui.QFont()
        font.setFamily("Nirmala Text")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.traducao_3.setFont(font)
        self.traducao_3.setStyleSheet("background-color: lightblue; /* Azul claro */\n"
"")
        self.traducao_3.setText("")
        self.traducao_3.setObjectName("traducao_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Cadastro"))
        self.label_4.setText(_translate("Form", "Email:"))
        self.label_5.setText(_translate("Form", "Senha:"))
        self.confirm_4.setText(_translate("Form", "Voltar"))
        self.confirm_5.setText(_translate("Form", "Cadastrar"))
