# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_inicial.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class tela_inicial(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(747, 597)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(150, 60, 461, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.confirm = QtWidgets.QPushButton(Form)
        self.confirm.setGeometry(QtCore.QRect(140, 180, 101, 51))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.confirm.setFont(font)
        self.confirm.setStyleSheet("QPushButton {\n"
"    background-color:White;\n"
"    color: black;\n"
"    border-radius: 10px;\n"
"    border: 2px solid black;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: Gray;\n"
"    color: white;\n"
"    border: 2px solid white;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:Gray;\n"
"    border: 2px solid yellow;\n"
"}")
        self.confirm.setObjectName("confirm")
        self.confirm_2 = QtWidgets.QPushButton(Form)
        self.confirm_2.setGeometry(QtCore.QRect(440, 180, 101, 51))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.confirm_2.setFont(font)
        self.confirm_2.setStyleSheet("QPushButton {\n"
"    background-color:White;\n"
"    color: black;\n"
"    border-radius: 10px;\n"
"    border: 2px solid black;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: Gray;\n"
"    color: white;\n"
"    border: 2px solid white;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:Gray;\n"
"    border: 2px solid yellow;\n"
"}")
        self.confirm_2.setObjectName("confirm_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Bem Vindo ao sistema da biblioteca!!"))
        self.confirm.setText(_translate("Form", "Cadastro"))
        self.confirm_2.setText(_translate("Form", "Login"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = tela_inicial()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
